name: "build"

on:
  push:
    tags:
      - "!v*"
    branches:
      - "*"

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: ${{ github.repository }}:${{github.sha}}-test
          cache-to: type=gha
      - name: Test
        run: |
          docker run --rm --entrypoint /usr/bin/testparm ${{ github.repository }}:${{github.sha}}-test -s
